// The roadmap issue of docs/workflow.md: its sub-issues, in order, are the order of work. This module
// loads them through an injected GitHub API function and renders the generated section of the
// roadmap issue; roadmap-sync.mjs runs it against GitHub. No I/O here, so roadmap.test.mjs covers it.

export const START = '<!-- roadmap:start -->';
export const END = '<!-- roadmap:end -->';
export const LABEL = 'roadmap';

/** How many open items at the top of the roadmap are Next. */
const NEXT = 3;

/** Sub-issues of sub-issues are loaded down to this depth; the roadmap's own items are depth 1. */
const MAX_DEPTH = 3;

const PAGE = 100;
const TITLE_IN_GRAPH = 48;

/**
 * @typedef {{ number: number, title: string, state: string }} IssueRef
 * @typedef {IssueRef & { id: number, blockedBy: IssueRef[], children: Item[] }} Item
 * @typedef {(path: string) => any} GitHubGet GET of a REST path below repos/<owner>/<name>/, parsed JSON
 */

const ref = (issue) => ({ number: issue.number, title: issue.title, state: issue.state });

const list = (get, path) => {
  const page = get(`${path}${path.includes('?') ? '&' : '?'}per_page=${PAGE}`);
  if (!Array.isArray(page)) throw new Error(`GitHub returned no list for ${path}`);
  if (page.length >= PAGE) throw new Error(`${path} has ${PAGE} or more entries; the roadmap supports fewer`);
  return page;
};

/**
 * Loads the open sub-issue tree of the roadmap issue, the open "blocked by" dependencies of every
 * open item, and the open issues labeled roadmap that are not placed in the tree.
 *
 * @param {GitHubGet} get
 * @param {number} roadmap number of the roadmap issue
 * @returns {{ items: Item[], unplaced: IssueRef[] }}
 */
export const loadRoadmap = (get, roadmap) => {
  const placed = new Set([roadmap]);
  const load = (number, depth) =>
    list(get, `issues/${number}/sub_issues`)
      .filter((issue) => issue.state === 'open')
      .map((issue) => {
        placed.add(issue.number);
        const blockedBy = issue.issue_dependencies_summary?.blocked_by === 0
          ? []
          : list(get, `issues/${issue.number}/dependencies/blocked_by`).filter((b) => b.state === 'open').map(ref);
        const children = depth >= MAX_DEPTH || issue.sub_issues_summary?.total === 0 ? [] : load(issue.number, depth + 1);
        return { ...ref(issue), id: issue.id, blockedBy, children };
      });
  const items = load(roadmap, 1);
  const unplaced = list(get, `issues?labels=${LABEL}&state=open`)
    .filter((issue) => !issue.pull_request && !placed.has(issue.number))
    .map(ref);
  return { items, unplaced };
};

// Mermaid labels: '#' starts an entity code, so it is written as one; quotes and brackets likewise.
const label = (text) =>
  text.replace(/#/g, '#35;').replace(/"/g, '#quot;').replace(/</g, '#lt;').replace(/>/g, '#gt;');

const shorten = (text) => (text.length > TITLE_IN_GRAPH ? `${text.slice(0, TITLE_IN_GRAPH - 1).trimEnd()}…` : text);

const node = (issue) => `n${issue.number}`;

/**
 * The generated section of the roadmap issue, between START and END: the order as a list with Next
 * marked, labeled issues that are not placed yet, and a Mermaid graph. In the graph the roadmap items
 * form a chain in their order (solid arrows), sub-issues hang off their parent (plain lines) and
 * "blocked by" dependencies are dotted arrows. Closed issues are left out.
 *
 * @param {{ items: Item[], unplaced?: IssueRef[], next?: number }} roadmap
 */
export const renderRoadmap = ({ items, unplaced = [], next = NEXT }) => {
  const open = (issues) => issues.filter((issue) => issue.state === 'open');
  const top = open(items);
  const lines = [
    START,
    '<!-- Generated by scripts/workflow/roadmap-sync.mjs from the sub-issues of this issue. Edits between these markers are overwritten. -->',
    '',
    '### Order',
    '',
  ];

  const order = (issues, indent) => {
    open(issues).forEach((issue, index) => {
      const marker = indent ? '- ' : `${index + 1}. `;
      const isNext = !indent && index < next;
      lines.push(`${'   '.repeat(indent)}${marker}#${issue.number}${isNext ? ' **Next**' : ''}`);
      order(issue.children ?? [], indent + 1);
    });
  };
  if (top.length === 0) lines.push('No open roadmap items.');
  else order(top, 0);

  if (unplaced.length > 0) {
    lines.push('', `**Not placed yet** (labeled \`${LABEL}\`, not a sub-issue): ${unplaced.map((i) => `#${i.number}`).join(', ')}`);
  }

  if (top.length > 0) {
    const declared = new Set();
    const graph = ['flowchart TD'];
    const edges = [];
    const declare = (issue, text, cls) => {
      if (declared.has(issue.number)) return;
      declared.add(issue.number);
      graph.push(`  ${node(issue)}["${label(text)}"]${cls ? `:::${cls}` : ''}`);
    };
    const walk = (issues, parent, depth) => {
      open(issues).forEach((issue, index) => {
        const prefix = depth === 0 ? `${index + 1} · ` : '';
        declare(issue, `${prefix}#${issue.number} ${shorten(issue.title)}`, depth === 0 && index < next ? 'next' : '');
        if (parent) edges.push(`  ${parent} --- ${node(issue)}`);
        else if (index > 0) edges.push(`  ${node(open(issues)[index - 1])} --> ${node(issue)}`);
        walk(issue.children ?? [], node(issue), depth + 1);
      });
    };
    walk(top, null, 0);
    const blocks = (issues) => {
      for (const issue of open(issues)) {
        for (const blocker of open(issue.blockedBy ?? [])) {
          declare(blocker, `#${blocker.number} ${shorten(blocker.title)}`, 'external');
          edges.push(`  ${node(blocker)} -. blocks .-> ${node(issue)}`);
        }
        blocks(issue.children ?? []);
      }
    };
    blocks(top);
    lines.push(
      '',
      '### Graph',
      '',
      '```mermaid',
      ...graph,
      ...edges,
      '  classDef next stroke-width:3px',
      '  classDef external stroke-dasharray:4 3',
      '```',
    );
  }

  lines.push(END);
  return lines.join('\n');
};

/** Replaces the section between START and END in the issue body; without markers it goes first. */
export const replaceGenerated = (body, generated) => {
  const start = body.indexOf(START);
  const end = start === -1 ? -1 : body.indexOf(END, start);
  if (end === -1) return body ? `${generated}\n\n${body}` : generated;
  return body.slice(0, start) + generated + body.slice(end + END.length);
};

/**
 * The body of the sub-issue priority request that moves one sub-issue among its siblings, or null
 * when it is already there.
 *
 * @param {{ number: number, id: number }[]} siblings sub-issues of the parent, in order
 * @param {number} number the issue to move
 * @param {{ top?: boolean, before?: number, after?: number }} position exactly one of them
 */
export const moveRequest = (siblings, number, position) => {
  const find = (n) => {
    const issue = siblings.find((sibling) => sibling.number === n);
    if (!issue) throw new Error(`#${n} is not a sub-issue of this parent`);
    return issue;
  };
  const given = ['top', 'before', 'after'].filter((key) => position[key] !== undefined && position[key] !== false);
  if (given.length !== 1) throw new Error('Give exactly one of --top, --before <issue> or --after <issue>.');
  const issue = find(number);
  const target = position.top ? siblings[0] : find(position.before ?? position.after);
  if (target.number === number) return null;
  const index = siblings.indexOf(issue);
  const targetIndex = siblings.indexOf(target);
  if (position.after !== undefined && index === targetIndex + 1) return null;
  if (position.after === undefined && index === targetIndex - 1) return null;
  return position.after !== undefined
    ? { sub_issue_id: issue.id, after_id: target.id }
    : { sub_issue_id: issue.id, before_id: target.id };
};
